name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      env:
        OPENTOK_KEY: ${{ secrets.OPENTOK_KEY }}
        OPENTOK_SECRET: ${{ secrets.OPENTOK_SECRET }}
